# Generated by Django 6.0 on 2026-05-20 18:20

import research_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=2000, unique=True, validators=[research_sessions.models._validate_repo_source]),
        ),
    ]
